POST http://localhost:5000/api/member/addMember?userId=64aa2d2c2ba94384ea3d0fb0&propertyId=64aa43b294501460f5e68341
Content-Type:application/json

{
    "name":"Owner",
    "phone":"9007453397",
    "doj":"15-07-2023",
    "designation":"Admin"
}