PUT http://localhost:5000/api/food/updateFood?userId=64aa2d2c2ba94384ea3d0fb0&propertyId=64aa43b294501460f5e68341
Content-Type:application/json

{
    "title":"Monday",
    "breakfast":"Chole Bhature",
    "lunch":"Rice,Dal,Paneer Pasanda,Raita,Chutney",
    "snacks":"Tea Biscuits",
    "dinner":"Roti,Chicken"
}