POST http://localhost:5000/api/contacts/addContactType
Content-Type:application/json

{
    "userId":"66b653631ca7d312dd6ff5fe",
    "propertyId":"66b653631ca7d312dd6ff5fe",
    "contactType":"Plumber"
}